CREATE TABLE ligne (
    route_id      text PRIMARY KEY,
    numero        text NOT NULL,
    nom           text,
    mode          text NOT NULL CHECK (mode IN ('tram', 'metro', 'bus')),
    couleur       text,
    couleur_texte text
);

CREATE TABLE arret (
    stop_id        text PRIMARY KEY,
    nom            text NOT NULL,
    nom_nl         text,
    latitude       double precision NOT NULL,
    longitude      double precision NOT NULL,
    accessible_pmr boolean
);

CREATE TABLE trace (
    shape_id   text PRIMARY KEY,
    points     jsonb NOT NULL,
    longueur_m integer
);

CREATE TABLE service_jour (
    service_id text NOT NULL,
    date       date NOT NULL,
    PRIMARY KEY (service_id, date)
);
CREATE INDEX idx_service_jour_date ON service_jour (date);

CREATE TABLE patron (
    patron_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id    text NOT NULL REFERENCES ligne (route_id),
    sens        smallint NOT NULL CHECK (sens IN (0, 1)),
    destination text,
    shape_id    text REFERENCES trace (shape_id),
    duree_s     integer NOT NULL
);
CREATE INDEX idx_patron_ligne_sens ON patron (route_id, sens);

CREATE TABLE patron_arret (
    patron_id        bigint NOT NULL REFERENCES patron (patron_id) ON DELETE CASCADE,
    ordre            smallint NOT NULL,
    stop_id          text NOT NULL REFERENCES arret (stop_id),
    decalage_s       integer NOT NULL,
    distance_trace_m integer,
    PRIMARY KEY (patron_id, ordre)
);
CREATE INDEX idx_patron_arret_arret ON patron_arret (stop_id);

CREATE TABLE course (
    course_id      text PRIMARY KEY,
    patron_id      bigint NOT NULL REFERENCES patron (patron_id),
    service_id     text NOT NULL,
    heure_depart_s integer NOT NULL,
    accessible_pmr boolean
);
CREATE INDEX idx_course_service_depart ON course (service_id, heure_depart_s);
CREATE INDEX idx_course_patron ON course (patron_id);

CREATE TABLE passages_ligne_heure (
    route_id    text NOT NULL REFERENCES ligne (route_id),
    sens        smallint NOT NULL CHECK (sens IN (0, 1)),
    type_jour   text NOT NULL CHECK (type_jour IN ('semaine', 'samedi', 'dimanche')),
    heure       smallint NOT NULL CHECK (heure BETWEEN 0 AND 27),
    nb_passages numeric(8, 2) NOT NULL,
    PRIMARY KEY (route_id, sens, type_jour, heure)
);

CREATE TABLE import_flux (
    feed_version text PRIMARY KEY,
    date_debut   date NOT NULL,
    date_fin     date NOT NULL,
    importe_le   timestamptz NOT NULL DEFAULT now()
);
