spring.application.name=bxl-transit-explorer
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5434}/${POSTGRES_DB:bxl}
spring.datasource.username=${POSTGRES_USER:bxl}
spring.datasource.password=${POSTGRES_PASSWORD:bxl_dev}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
